### ISSUE TITLE
επιπλέον links προς αντίστοιχους δικτυακούς τόπους

### ISSUE THREAD

**Issue by psampa** [gkarka/HEAL-DSpace#39]
openAire,
openDOAR,
ROAR,
Ranking of Web Repositories,
SHERPA ROMEO,
Openarchives.gr
Εθνικό Αρχείο Διδακτορικών Διατριβών

**Comment by gkarka** [comment]
Χρειαζόμαστε απαραίτητα το logo της Υπηρεσίας SHEPPA/ROMEO για τις δημοσιεύσεις.

SHERPA/RoMEO Logo
http://www.sherpa.ac.uk/romeo/index.php?la=en&fIDnum=|&mode=simple

Χρειαζόμαστε επίσης απαραίτητα το logo του ΕΚΤ (ΕΑΔΔ).

http://phdtheses.ekt.gr/eadd/

Τα υπόλοιπα είναι προαιρετικά και θα μπορούσαμε να τα παραλείψουμε ή να τα έχουμε κάτω από το λεκτικό «Χρήσιμοι Σύνδεσμοι».

openAire
https://www.openaire.eu/el

Europeana
http://www.europeana.eu/portal/

http://repositories.webometrics.info/
